// get all alive mobs of x faction
/proc/alive_n_of_side(x)
	. = 0
	switch (x)
		if (CIVILIAN)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == CIVILIAN)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (BRITISH)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == BRITISH)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (PIRATES)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == PIRATES)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (SPANISH)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == SPANISH)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (PORTUGUESE)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == PORTUGUESE)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (FRENCH)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == FRENCH)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (INDIANS)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == INDIANS)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (DUTCH)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == DUTCH)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (ITALIAN)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == ITALIAN)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (JAPANESE)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == JAPANESE)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (RUSSIAN)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == RUSSIAN)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (CHECHEN)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == CHECHEN)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (FINNISH)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == FINNISH)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (NORWEGIAN)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == NORWEGIAN)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (SWEDISH)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == SWEDISH)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (DANISH)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == DANISH)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (ROMAN)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == ROMAN)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (GREEK)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == GREEK)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (ARAB)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == ARAB)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (GERMAN)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == GERMAN)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.

		if (AMERICAN)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == AMERICAN)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (VIETNAMESE)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == VIETNAMESE)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.

		if (CHINESE)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == CHINESE)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.

		if (FILIPINO)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == FILIPINO)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (POLISH)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == POLISH)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (BLUEFACTION)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == BLUEFACTION)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (REDFACTION)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == REDFACTION)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (CAFR)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == CAFR)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
		if (TSFSR)
			for (var/mob/living/human/H in player_list)
				if (H.original_job && H.stat != DEAD)
					if (H.original_job.base_type_flag() == TSFSR)
						BATTLEREPORT_VARIABLE_CHECK(H)
							++.
