#define MAP_TOWER "TOWER"
#define MAP_CITY "CITY"
#define MAP_FOREST "FOREST"
#define MAP_SURVIVAL "SURVIVAL"
#define MAP_LANDING "LANDING"
#define MAP_CAMP "CAMP"
#define MAP_REICHSTAG "REICHSTAG"
#define MAP_PARTISAN "PARTISAN"
#define MAP_ESCORT "ESCORT"
#define MAP_FOREST_NEW "FOREST_NEW"
#define MAP_ISLAND "ISLAND"
#define MAP_NAVAL "NAVAL"

#define MODE_WAR 1
#define MODE_GERMAN_OCCUPATION 2
#define MODE_SOVIET_OCCUPATION 3