#define MAP_NAVAL "NAVAL"
#define MAP_VOYAGE "VOYAGE"
#define MAP_ISLAND "ISLAND"
#define MAP_ROBUSTA "ROBUSTA"
#define MAP_BATTLEROYALE "BATTLEROYALE"
#define MAP_SUPPLY_RAID "SUPPLY_RAID"
#define MAP_COLONY "COLONY"
#define MAP_TRIBES "TRIBES"
#define MAP_FOUR_COLONIES "FOUR_COLONIES"
#define MAP_RECIFE "RECIFE"
#define MAP_CURSED_ISLAND "CURSED_ISLAND"
#define MAP_FIELDS "FIELDS"
#define MAP_HUNT "HUNT"

#define MAP_HERACLEA "HERACLEA"
#define MAP_SIEGE "SIEGE"

#define MAP_CAMP "CAMP"
#define MAP_KARAK "KARAK"

#define MODE_WAR 1