#define MAP_NAVAL "NAVAL"
#define MAP_VOYAGE "VOYAGE"
#define MAP_ISLAND "ISLAND"
#define MAP_ROBUSTA "ROBUSTA"
#define MAP_BATTLEROYALE "BATTLEROYALE"
#define MAP_SUPPLY_RAID "SUPPLY_RAID"
#define MAP_COLONY "COLONY"
#define MAP_FOUR_COLONIES "FOUR_COLONIES"
#define MAP_RECIFE "RECIFE"
#define MAP_CURSED_ISLAND "CURSED_ISLAND"
#define MAP_FIELDS "FIELDS"
#define MAP_HUNT "HUNT"

#define MAP_HERACLEA "HERACLEA"
#define MAP_SIEGE "SIEGE"

#define MAP_CAMP "CAMP"
#define MAP_KARAK "KARAK"

#define MAP_LITTLE_CREEK "LITTLE_CREEK"
#define MAP_LITTLE_CREEK_TDM "LITTLE_CREEK_TDM"

#define MAP_TRIBES "TRIBES"
#define MAP_CIVILIZATIONS "CIVILIZATIONS"
#define MAP_NOMADS "NOMADS"
#define MAP_NOMADS_DESERT "NOMADS_DESERT"
#define MAP_NOMADS_ICE_AGE "NOMADS_ICE_AGE"
#define MAP_NOMADS_JUNGLE "NOMADS_JUNGLE"
#define MAP_NOMADS_DIVIDE "NOMADS_DIVIDE"
#define MAP_NOMADS_MOUNTAIN "NOMADS_MOUNTAIN"

#define MAP_NOMADS_EXTENDED "NOMADS_EXTENDED"
#define MODE_WAR 1