#define DAMAGE_LOW 48
#define DAMAGE_MEDIUM 55
#define DAMAGE_MEDIUM_HIGH 60
#define DAMAGE_HIGH 80
#define DAMAGE_VERY_HIGH 100
#define DAMAGE_OH_GOD 200

/*
#define DAMAGE_LOW 40
#define DAMAGE_MEDIUM 48
#define DAMAGE_MEDIUM_HIGH 56
#define DAMAGE_HIGH 72
#define DAMAGE_VERY_HIGH 96
#define DAMAGE_OH_GOD 200
*/