#define STAT_MAX 250
#define STAT_VERY_VERY_HIGH 200
#define STAT_VERY_HIGH 160
#define STAT_HIGH 140
#define STAT_MEDIUM_HIGH 120
#define STAT_NORMAL 100
#define STAT_MEDIUM_LOW 90
#define STAT_LOW 80
#define STAT_VERY_LOW 70
#define STAT_VERY_VERY_LOW 50
#define STAT_LOWEST 1

#define ALL_STATS list(STAT_LOWEST, STAT_VERY_VERY_LOW, STAT_VERY_LOW, STAT_LOW, STAT_MEDIUM_LOW, STAT_NORMAL, STAT_MEDIUM_HIGH, STAT_HIGH, STAT_VERY_HIGH, STAT_MAX)

#define GET_STAT_COEFF(constant) constant/100
#define GET_MIN_STAT_COEFF(constant) (constant-5)/100