/obj/map_metadata/east_los_santos
	ID = MAP_EAST_LOS_SANTOS
	title = "East Los Santos"
	lobby_icon = "icons/lobby/east_los_santos.png"
	no_winner = "The fight for the hoods is still going on."
	caribbean_blocking_area_types = list()
	respawn_delay = 0
	faction_organization = list(
		AMERICAN,
		INDIANS,)
	roundend_condition_sides = list()
	age = "1992"
	ordinal_age = 7
	faction_distribution_coeffs = list(AMERICAN = 0.5, INDIANS = 0.5)
	battle_name = "East Los Santos"
	mission_start_message = "<font size=4>Grove Street and Ballas are competing against each other to capture all the territories in East Los Santos.<br> Points are generated by capturing turfs. The gang with most points (50) wins!"
	faction1 = AMERICAN
	faction2 = INDIANS
	grace_wall_timer = 3000
	gamemode = "Turf War"
	songs = list(
		"Compton\'s Most Wanted - Hood Took Me Under:1" = "sound/music/hood_took_me_under.ogg",)
	var/grove_points = 0
	var/ballas_points = 0
	var/a1_control = "None"
	/*var/a2_control = "None"
	var/a3_control = "None"
	var/a4_control = "None"*/

/obj/map_metadata/east_los_santos/proc/points_check()
	if (processes.ticker.playtime_elapsed > 4800)
		var/c1 = 0
		var/c2 = 0
		var/cust_color = "white"
		for (var/mob/living/human/H in player_list)
			var/area/temp_area = get_area(H)
			if (istype(temp_area, /area/caribbean/no_mans_land/capturable/one))
				if (H.faction_text == "AMERICAN" && H.stat == CONSCIOUS)
					c1++
				else if (H.faction_text == "INDIANS" && H.stat == CONSCIOUS)
					c2++
		if ((c1 == c2) && c1 != 0)
			a1_control = "none"
			cust_color= "white"
		else if (c1 > c2)
			a1_control = "Grove Street"
			cust_color= "green"
		else if (c2 > c1)
			a1_control = "Ballas"
			cust_color= "purple"
		if (a1_control != "none")
			if (a1_control == "Grove Street")
				cust_color = "green"
				grove_points++
			else if (a1_control == "Ballas")
				cust_color = "purple"
				ballas_points++
			else
				cust_color = "white"
			world << "<big><font color='[cust_color]'><b>Area 1</b>: [a1_control]</font></big>"
		else
			world << "<big><b>Area 1</b>: Nobody</big>"

/obj/map_metadata/east_los_santos/job_enabled_specialcheck(var/datum/job/J)
	..()
	if (J.is_gta == TRUE)
		. = TRUE
	else
		. = FALSE

/obj/map_metadata/east_los_santos/roundend_condition_def2name(define)
	..()
	switch (define)
		if (INDIANS)
			return "Ballas"
		if (AMERICAN)
			return "Grove Street"

/obj/map_metadata/east_los_santos/roundend_condition_def2army(define)
	..()
	switch (define)
		if (INDIANS)
			return "Ballas"
		if (AMERICAN)
			return "Grove Street"

/obj/map_metadata/east_los_santos/army2name(army)
	..()
	switch (army)
		if ("Ballas")
			return "Ballas"
		if ("Grove Street")
			return "Grove Street"

/obj/map_metadata/east_los_santos/cross_message(faction)
	if (faction == AMERICAN)
		return "<font size = 4>Both teams may now cross the invisible wall!</font>"
	else if (faction == INDIANS)
		return ""
	else
		return ""

/obj/map_metadata/east_los_santos/reverse_cross_message(faction)
	if (faction == AMERICAN)
		return "<span class = 'userdanger'>Both teams may no longer cross the invisible wall!</span>"
	else if (faction == INDIANS)
		return ""
	else
		return ""

//////////////MAP SPECIFIC OBJECTS///////////////////

/obj/item/clothing/under/ballas1
	name = "white t-shirt and purple shorts"
	desc = "An oversized white t-shirt and purple cargo shorts."
	icon_state = "ballas1"
	item_state = "ballas1"
	worn_state = "ballas1"
	body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS|ARMS

/obj/item/clothing/under/ballas2
	name = "baggy black clothing"
	desc = "An oversized black outfit."
	icon_state = "ballas2"
	item_state = "ballas2"
	worn_state = "ballas2"
	body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS|ARMS

/obj/item/clothing/under/ballas3
	name = "purple shirt and khaki pants"
	desc = "An oversized purple shirt and khaki cargo pants."
	icon_state = "ballas3"
	item_state = "ballas3"
	worn_state = "ballas3"
	body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS|ARMS

/obj/item/clothing/under/grove1
	name = "green sweatshirt and jeans"
	desc = "An oversized green sweatshirt and jeans."
	icon_state = "grove1"
	item_state = "grove1"
	worn_state = "grove1"
	body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS|ARMS

/obj/item/clothing/under/grove2
	name = "green checkered outfit"
	desc = "A green checkered shirt and beige pants."
	icon_state = "grove2"
	item_state = "grove2"
	worn_state = "grove2"
	body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS|ARMS

/obj/item/clothing/under/grove3
	name = "green jersey and jeans"
	desc = "A green basketball jersey and black jeans."
	icon_state = "grove3"
	item_state = "grove3"
	worn_state = "grove3"
	body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS|ARMS

/obj/item/clothing/head/custom/custom_beanie/black
	color = "#0d0d0d"
	uncolored1 = FALSE

/obj/item/clothing/head/bandana_ballas
	name = "purple bandana"
	desc = "A purple bandana tied in the front."
	icon_state = "bandana_ballas1"
	item_state = "bandana_ballas1"
	worn_state = "bandana_ballas1"
	flags_inv = BLOCKHEADHAIR

/obj/item/clothing/head/bandana_ballas/two
	icon_state = "bandana_ballas2"
	item_state = "bandana_ballas2"
	worn_state = "bandana_ballas2"

/obj/item/clothing/head/bandana_grove
	name = "green bandana"
	desc = "A green bandana tied in the front."
	icon_state = "bandana_grove"
	item_state = "bandana_grove"
	worn_state = "bandana_grove"
	flags_inv = BLOCKHEADHAIR