/mob/living/simple_animal/hostile/dinosaur/pachycephalosaurus
	name = "Pachycephalosaurus"
	desc = "Pachy for short."
	icon = 'icons/mob/animal_big.dmi'
	icon_state = "pachycephalosaurus"
	icon_living = "pachycephalosaurus"
	icon_dead = "pachycephalosaurus_dead"
	icon_gib = "pachycephalosaurus_dead"
	speak = list("skreee!","skrrrrr!","krrrr")
	speak_emote = list("rawr", "hiss")
	emote_hear = list("rawrs","hisses")
	emote_see = list("stares ferociously", "grunts")
	speak_chance = TRUE
	move_to_delay = 4
	see_in_dark = 6
	meat_type = /obj/item/weapon/reagent_containers/food/snacks/meat
	response_help  = "pets"
	response_disarm = "gently pushes aside"
	response_harm   = "pokes"
	stop_automated_movement_when_pulled = FALSE
	maxHealth = 120
	health = 120
	melee_damage_lower = 30
	melee_damage_upper = 35
	mob_size = MOB_LARGE
	predatory_carnivore = 1
	carnivore = 1
	faction = "neutral"
